#!/bin/sh /etc/rc.common
#
# Copyright (C) 2006-2011 OpenWrt.org


START=95
STOP=15

USE_PROCD=1
PROG=/usr/sbin/telegram_bot

start_service () {
    service_start ${PROG}
}

stop_service() {
    kill $(pgrep -f telegram_bot)
}

restart(){
    stop_service
    sleep 1
    start_service
}
