#!/bin/sh
#
PATH='/usr/bin:/usr/sbin:/bin:/sbin'

token=`uci get telegram.default.token`
rupor=`uci get telegram.default.rupor`
api="https://api.telegram.org/bot$token"
offset_file=/tmp/telegram_offset

sleep 10
keyboard='{"keyboard": [["/snap \uD83D\uDCF7","/guard \uD83D\uDC6E","/relay \uD83D\uDCA1"],["/system \uD83D\uDCCA","/reboot \uD83D\uDCA9","/fixes \uD83D\uDD25"]],"resize_keyboard":true,"one_time_keyboard":false}'
curl -k -s -X POST $api/sendMessage -d chat_id=$rupor -d parse_mode=Markdown --data-urlencode text="Router started." &
curl -k -s -X POST -H "Charset: UTF-8"  $api/sendMessage -d chat_id=$rupor -d "reply_markup=${keyboard}" -d "text=Please insert command:" &

offset=0
if [ -f "$offset_file" ] ; then
	offset=$( cat $offset_file )
else
	echo $offset > $offset_file
fi

reply_to_msg () {
	msg_id=$1
	origin=$2
	eval toReturn="$3"
        curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=HTML --data-urlencode text="$toReturn" &
}

while [ true ]
do
	updates=$(curl -s -k -X GET $api/getUpdates?offset=$offset)
	status=$(jsonfilter -s "$updates" -e $.ok)
	if [ $status = 'true' ]; then
		update_ids=$(jsonfilter -s "$updates" -e $.result[*].update_id)
		for update_id in $update_ids
		do
			offset=$((update_id+1))
			echo $offset > $offset_file
			origin=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.chat.id")
			msg_id=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].message.message_id")
			command=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.text")
			is_a_cmd=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].message.entities[*].type")
			query_ans=$(jsonfilter -s "$updates" -e "$.result[@.update_id=$update_id].callback_query.id")
			origin_ans=$(jsonfilter -s "$updates"  -e "$.result[@.update_id=$update_id].callback_query.message.chat.id")
			if [[ "$origin" != "$rupor" && "$origin_ans" != "$rupor" ]];then
				curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="This is a Private bot." &
				curl -k -s -X POST $api/leaveChat -d chat_id=$origin &
			else
				if [ "$is_a_cmd" ==  "bot_command" ]; then
					cmd=$(echo $command |  awk '{print $1}')
					DATE=`date +%Y-%m-%d_%H:%M:%S`
					RETURN_TEXT=""
					case "$cmd" in
						("/reboot")
							echo "[ $DATE ] reboot!" | logger -t "telegram_bot" -p daemon.info
							informex_reboot=$("tg_reboot.sh")
							reply_to_msg $msg_id $origin "\${informex_reboot}"
							;;
						("/relay")
							echo "[ $DATE ] relay!" | logger -t "telegram_bot" -p daemon.info
							informex_relay=$("tg_relay.sh")
							reply_to_msg $msg_id $origin "\${informex_relay}"
                                                        ;;
						("/system")
							echo "[ $DATE ] system!" | logger -t "telegram_bot" -p daemon.info
							clients=$("./functions/memory_info.sh")
							RETURN_TEXT="$(printf "Memory informations: \n$clients")"
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
                                                        ;;
						("/guard")
							echo "[ $DATE ] guard!" | logger -t "telegram_bot" -p daemon.info
							text="Нету денег - нет охраны !"
							RETURN_TEXT="$(printf "Informex: \n$text")"
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
                                                        ;;
						(*)
							echo "[ $DATE ] $cmd command not enabled" | logger -t "telegram_bot" -p daemon.info
							RETURN_TEXT="This command is not enabled."
							reply_to_msg $msg_id $origin "\${RETURN_TEXT}"
							;;
					esac
				else
					curl -k -s -X POST $api/sendMessage -d reply_to_message_id=$msg_id -d chat_id=$origin -d parse_mode=Markdown --data-urlencode text="Is not a command." &
				fi
			fi
		done
	fi
	sleep 1
done &
