
STAGING_DIR=/var/www/builder/data/trunk/build_ng/openwrt/staging_dir
export STAGING_DIR
CFLAGS=-I.
#
# Atheros
CC= ~/trunk/build_ng/openwrt/staging_dir/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc
#
# Broadcom
#CC= ~/trunk/build_ng/openwrt/staging_dir/toolchain-mips_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc



flygps:
	$(CC) -o flygps flygps003.c
