#!/bin/sh

ENABLED=yes
PROCS=accel-pppd
ARGS="-d -c /opt/etc/accel-ppp.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
