#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
# Copyright (C) ZFTLAB.org

START=50

USE_PROCD=1
PROG=/usr/sbin/httpd

start_service() {
  if [ $(uci_get "microbe.webadmin.enable") = "1" ] ; then
    #
    hostname=$(uci_get "system.@system[0].hostname")
    project=$(uci_get "microbe.webadmin.project")
    password=$(uci_get "microbe.webadmin.password")
    port=$(uci_get "microbe.webadmin.port")
    home=$(uci_get "microbe.webadmin.home")
    #
    mkdir -p /tmp/etc
    echo -e "#\nA:*\n/cgi-bin:$project:$password\n#\n" >/tmp/etc/httpd.conf
    #
    if [ -s /tmp/etc/httpd.conf ] ; then
      procd_open_instance
      procd_set_param command "$PROG" -p "$port" -h "$home" -c /tmp/etc/httpd.conf -r "$hostname"
      procd_close_instance
    else
      return 1
    fi
  else
    return 1
  fi
}
