#!/bin/sh

set -eu

if [ ! -d .git ]; then
    (cd "$(dirname $0)/.." && ./3pp/update)
    exit $?
fi

pull()
{
    git subtree pull --prefix "$1" "$2" master --squash
}

pull 3pp/catch https://github.com/philsquared/Catch.git
pull 3pp/integer_seq https://github.com/erijo/integer_seq.git
pull 3pp/tinyxml2 https://github.com/leethomason/tinyxml2.git
pull 3pp/rapidjson https://github.com/miloyip/rapidjson.git
