#!/bin/sh
#
# Simple script updates the aprx configuration file
# by BG5HHP
# 

#CALL=bg5hhp-12
CALL=$1
[ -z $CALL ] && CALL=`hostname -s`
[ -z $CALL ] && echo "missing CALLSIGN" && exit
REMOTE=https://aprs.hamclub.net/openwrt/config/${CALL}.conf
LOCAL=/etc/aprx.conf
rm -f .aprx.conf.upd
wget -q  ${REMOTE} -O .aprx.conf.upd
if [ $? -ne 0 ]
then
  echo "remote config file is not found!" 
  exit
fi

MD5_REMOTE=`openssl md5 .aprx.conf.upd |awk '{print $2}'`
MD5_LOCAL=empty
[ -f $LOCAL ] && MD5_LOCAL=`openssl md5 ${LOCAL} |awk '{print $2}'`
echo "L: ${MD5_LOCAL}"
echo "R: ${MD5_REMOTE}"
if [ "${MD5_LOCAL}" = "${MD5_REMOTE}" ]
then
  echo "Config not changed"
  exit 1
fi

echo "Updating ${LOCAL}..."
cp .aprx.conf.upd ${LOCAL}
[ $? -eq 0 ] || echo "Update failed!"

#done!
exit 0
