#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='Octonix_ugb'
	set system.@system[0].timezone='EET-2EEST,M3.5.0/3,M10.5.0/4'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyACM0'
	set network.wan1.service='evdo'
	set network.wan1.username='IT'
	set network.wan1.password='IT'
	set network.wan1.metric='1'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='wlan'
	commit network
	set network.wan2=interface
	set network.wan2.proto='3g'
	set network.wan2.device='/dev/ttyACM1'
	set network.wan2.service='umts'
	set network.wan2.apn='www.kyivstar.net'
	set network.wan2.metric='2'
	set network.wan2.ipv6='0'
	set network.wan2.keepalive='3'
	set network.wan2.gpio='qss'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='vtun'
	set network.vtun0.server='vbox3.flymon.net'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set network.vtun1='interface'
	set network.vtun1.proto='vtun'
	set network.vtun1.server='A.B.C.D'
	set network.vtun1.name='ugb011'
	set network.vtun1.password='test2016'
	set network.vtun1.mode='ether'
	set network.vtun1.bridge='br-lan'
	commit network
	set snmpd.default='snmpd'
	set snmpd.default.community='ugb'
	set snmpd.default.contact='Octonix'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1,3g-wan2'
	commit snmpd
EOF

rm /etc/hotplug.d/usb/20-usb_mode
# echo "/etc/init.d/usbmode start" >/etc/hotplug.d/usb/20-usb_mode

echo -e "#\n# Reset USB host\n(echo 0 > /sys/class/gpio/gpio8/value; sleep 5; echo 1 > /sys/class/gpio/gpio8/value) >/dev/null 2>&1\n" >/etc/rc.local
echo -e "#\n# Start dual routing\n/usr/sbin/checklink.sh >/dev/null 2>&1 &\n" >>/etc/rc.local
echo -e "#\n# Start checker\n(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >>/etc/rc.local
echo -e "#\n# Start snmpd\n(while true ; do sleep 5; /usr/bin/mini_snmpd -n -c ugb -L World -C Intertelecom -t 1 -d /overlay,/tmp -i br-lan,3g-wan1,3g-wan2 >/dev/null 2>&1; done) &\n" >>/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local


exit 0
