#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='Octonix_msl'
	set system.@system[0].timezone='EET-2EEST,M3.5.0/3,M10.5.0/4'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyACM0'
	set network.wan1.service='evdo'
	set network.wan1.username='IT'
	set network.wan1.password='IT'
	set network.wan1.metric='1'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='20'
	set network.wan1.indicator='1'
	commit network
	set network.wan2=interface
	set network.wan2.proto='3g'
	set network.wan2.device='/dev/ttyACM1'
	set network.wan2.service='umts'
	set network.wan2.apn='www.kyivstar.net'
	set network.wan2.metric='2'
	set network.wan2.ipv6='0'
	set network.wan2.keepalive='3'
	set network.wan2.gpio='17'
	set network.wan2.indicator='2'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='vtun'
	set network.vtun0.server='vbox3.flymon.net'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set network.vtun1='interface'
	set network.vtun1.proto='vtun'
	set network.vtun1.server='A.B.C.D'
	set network.vtun1.name='msl011'
	set network.vtun1.password='test2016'
	set network.vtun1.mode='ether'
	set network.vtun1.bridge='br-lan'
	commit network
	set snmpd.default='snmpd'
	set snmpd.default.community='msl'
	set snmpd.default.contact='Octonix'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1,3g-wan2'
	commit snmpd
	set network.vpncs=route
	set network.vpncs.interface='vpn'
	set network.vpncs.target='10.100.0.0'
	set network.vpncs.netmask='255.255.255.248'
	commit network
EOF

echo "root:1234" | chpasswd

echo -e "#\n# Reset USBgpio\n(for n in '1' '2' '3' '4' '5' '6' '7' '8'; do usbgpio off $n; done) >/dev/null 2>&1\n" >/etc/rc.local
echo -e "#\n# Start checker\n(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >>/etc/rc.local
echo -e "#\n# Start snmpd\n(while true ; do sleep 5; /usr/bin/mini_snmpd -n -c msl -L World -C Intertelecom -t 1 -d /overlay,/tmp -i br-lan,3g-wan1,3g-wan2 >/dev/null 2>&1; done) &\n" >>/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local


exit 0
