#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='Energy-011'
	set system.@system[0].timezone='EET-2EEST,M3.5.0/3,M10.5.0/4'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyACM0'
	set network.wan1.service='evdo'
	set network.wan1.username='IT'
	set network.wan1.password='IT'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='20'
	set network.wan1.indicator='1'
	set network.wan1.limber='2'
	commit network
	set snmpd.default='snmpd'
	set snmpd.default.community='Energy'
	set snmpd.default.contact='Octonix'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1'
	commit snmpd
EOF


mv -f /etc/ser2net_octonix.conf /etc/ser2net.conf

echo -e "#\n# Reset USBgpio\n(for n in '1' '2' '3' '4' '5' '6' '7' '8'; do usbgpio off $n; done) >/dev/null 2>&1\n" >/etc/rc.local
echo -e "#\n# Start dual routing\n#/usr/sbin/checklink.sh >/dev/null 2>&1 &\n" >>/etc/rc.local
echo -e "#\n# Start ser2net\n(while true ; do sleep 5; stty -F /dev/ttyUSB0 hup; /usr/sbin/ser2net -d -p 2000 -c /etc/ser2net.conf >/dev/null 2>&1; done) &\n" >>/etc/rc.local
echo -e "#\n# Start checker\n#(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >>/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local


exit 0
