#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='Octonix_base'
	set system.@system[0].timezone='EET-2EEST,M3.5.0/3,M10.5.0/4'
	commit system

	delete network.globals
	delete network.lan.ip6assign
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyACM1'
	set network.wan1.service='evdo'
	set network.wan1.username='IT'
	set network.wan1.password='IT'
	set network.wan1.metric='1'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='20'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='vtun'
	set network.vtun0.server='vbox3.flymon.net'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
EOF

echo -e "#\n7777:raw:0:/dev/ttyRS485:9600 8DATABITS NONE 1STOPBIT -XONXOFF -RTSCTS LOCAL\n#\n" >/etc/ser2net.conf

echo -e "#\n# Start ser2net\n(while true ; do sleep 5; /usr/sbin/ser2net -d -c /etc/ser2net.conf >/dev/null 2>&1; done) &\n" >/etc/rc.local
echo -e "#\n# Start checker\n#(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >>/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local

exit 0
