#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='Octonix_mnp'
	set system.@system[0].timezone='EET-2EEST,M3.5.0/3,M10.5.0/4'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyACM0'
	set network.wan1.service='evdo'
	set network.wan1.username='IT'
	set network.wan1.password='IT'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='20'
	set network.wan1.indicator='1'
	commit network
	set network.wan2=interface
	set network.wan2.proto='3g'
	set network.wan2.device='/dev/ttyACM1'
	set network.wan2.service='umts'
	set network.wan2.apn='www.kyivstar.net'
	set network.wan2.ipv6='0'
	set network.wan2.keepalive='3'
	set network.wan2.gpio='17'
	set network.wan2.indicator='2'
	commit network
	set snmpd.default='snmpd'
	set snmpd.default.community='mnp'
	set snmpd.default.contact='Octonix'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1,3g-wan2'
	commit snmpd
	del openvpn.custom_config
	del openvpn.sample_server
	del openvpn.sample_client
	commit openvpn
	set openvpn.vpn1='openvpn'
	set openvpn.vpn1.enabled='1'
	set openvpn.vpn1.client='1'
	set openvpn.vpn1.remote='vpn.radcon.com.ua'
	set openvpn.vpn1.port='1194'
	set openvpn.vpn1.proto='udp'
	set openvpn.vpn1.tls_client='1'
	set openvpn.vpn1.dev='tun1'
	set openvpn.vpn1.mode='p2p'
	set openvpn.vpn1.route_delay='3'
	set openvpn.vpn1.verb='3'
	set openvpn.vpn1.keepalive='10 600'
	set openvpn.vpn1.persist_key='1'
	set openvpn.vpn1.persist_tun='1'
	set openvpn.vpn1.ca='/etc/openvpn/ca.crt'
	set openvpn.vpn1.cert='/etc/openvpn/cert.crt'
	set openvpn.vpn1.key='/etc/openvpn/cert.key'
	set openvpn.vpn1.auth_nocache='1'
	set openvpn.vpn1.script_security='4 system'
	set openvpn.vpn1.auth='SHA1'
	set openvpn.vpn1.pull='1'
	set openvpn.vpn1.comp_lzo='yes'
	commit openvpn
EOF

rm /etc/hotplug.d/usb/20-usb_mode
# echo "/etc/init.d/usbmode start" >/etc/hotplug.d/usb/20-usb_mode

echo -e "#\n# Reset USBgpio\n(for n in '1' '2' '3' '4' '5' '6' '7' '8'; do usbgpio off $n; done) >/dev/null 2>&1\n" >/etc/rc.local
echo -e "#\n# Start dual routing\n/usr/sbin/checklink.sh >/dev/null 2>&1 &\n" >>/etc/rc.local
echo -e "#\n# Start checker\n#(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >>/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local


exit 0
