#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='MyWiFi_micro'
	set system.@system[0].timezone='MSK-3'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set network.wan1=interface
	set network.wan1.type='bridge'
	set network.wan1.proto='dhcp'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='vtun'
	set network.vtun0.server='vbox3.flymon.net'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set wireless.radio0.channel='7'
	set wireless.radio0.disabled='0'
	set wireless.@wifi-iface[0].ssid='MyWiFi_micro'
	commit wireless
EOF

echo -e "#\nexit 0\n" >/etc/rc.local

exit 0
