#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='ZFT_Lab_base'
	set system.@system[0].timezone='MSK-3'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	commit network
	set network.port1='switch_port'
	set network.port1.device='switch0'
	set network.port1.port='1'
	set network.port1.disable='1'
	set network.port2='switch_port'
	set network.port2.device='switch0'
	set network.port2.port='2'
	set network.port2.disable='1'
	set network.port3='switch_port'
	set network.port3.device='switch0'
	set network.port3.port='3'
	set network.port3.disable='1'
	set network.port4='switch_port'
	set network.port4.device='switch0'
	set network.port4.port='4'
	set network.port4.disable='1'
	set network.port5='switch_port'
	set network.port5.device='switch0'
	set network.port5.port='5'
	set network.port5.disable='1'
	commit network
	set wireless.radio0.channel='7'
	set wireless.radio0.disabled='0'
	set wireless.@wifi-iface[0].ssid='FreeTest'
	commit wireless
	set snmpd.default='snmpd'
	set snmpd.default.community='public'
	set snmpd.default.contact='Boss'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1'
	commit snmpd
EOF

exit 0
