#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='DIR300_telemetry'
	set system.@system[0].timezone='MSK-3'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.wan=interface
	set network.wan.type='bridge'
	set network.wan.proto='dhcp'
	commit network
	set network.wan1=interface
	set network.wan1.proto='3g'
	set network.wan1.device='/dev/ttyMODEM1'
	set network.wan1.service='umts'
	set network.wan1.apn='internet'
	set network.wan1.ipv6='0'
	set network.wan1.keepalive='3'
	set network.wan1.gpio='0'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='none'
	set network.vtun0.server='my.server.org'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set wireless.radio0.channel='7'
	set wireless.radio0.disabled='0'
	set wireless.@wifi-iface[0].ssid='DIR300_telemetry'
	commit wireless
EOF

echo -e "#\nexit 0\n" >/etc/rc.local

exit 0
