#!/bin/sh

local mac
mac=$(fw_printenv -n ethaddr)

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='OpenIPC_HI35xx'
	set system.@system[0].timezone='MSK-3'
	commit system
	set microbe.webadmin.port='80'
	set microbe.webadmin.project='openipc'
	set microbe.pinger.checked='8.8.4.4'
	commit microbe
	delete network.globals
	delete network.wan6
	commit network
	delete network.lan.ip6assign
	set network.lan.macaddr=${mac}
	commit network
	set network.hilink=interface
	set network.hilink.ifname='eth1'
	set network.hilink.proto='dhcp'
	commit network
	set network.wan=interface
	set network.wan.proto='3g'
	set network.wan.device='/dev/ttyUSB0'
	set network.wan.service='umts'
	set network.wan.apn='internet'
	set network.wan.ipv6='0'
	set network.wan.keepalive='3'
	set network.wan.disabled='1'
	commit network
	set network.vlan=interface
	set network.vlan.ifname='eth0.490'
	set network.vlan.type='bridge'
	set network.vlan.proto='static'
	set network.vlan.ipaddr='172.28.200.80'
	set network.vlan.netmask='255.255.255.128'
	set network.vlan.gateway='172.28.200.1'
	set network.vlan.dns='77.88.8.8 8.8.4.4'
	commit network
	set network.vpn1=interface
	set network.vpn1.ifname='tun1'
	set network.vpn1.auto='1'
	set network.vpn1.proto='none'
	commit network
	set snmpd.default='snmpd'
	set snmpd.default.enable='1'
	set snmpd.default.community='openipc'
	set snmpd.default.location='World'
	set snmpd.default.contact='OpenIPC'
	set snmpd.default.interface='br-lan,3g-wan1,tun1'
	set snmpd.default.disk='/overlay,/tmp'
	commit snmpd
EOF


echo "root:openipc" | chpasswd

echo "#" >/etc/opkg/distfeeds.conf

echo -e "#\n# Start checker\n#(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local

exit 0
