#!/bin/sh

local mac
mac=$(fw_printenv -n ethaddr)

touch /etc/config/dbell

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='DBell_HI35xx'
	set system.@system[0].timezone='UTC'
	commit system
	delete network.globals
	delete network.wan6
	commit network
	delete network.lan.ip6assign
	set network.lan.macaddr=${mac}
	commit network
	set network.wifi=interface
	set network.wifi.ifname='ra0'
	set network.wifi.proto='dhcp'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='none'
	set network.vtun0.server='my.server.org'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set fstab.@mount[1].target='/mnt/photo'
	set fstab.@mount[2].target='/mnt/photo'
	commit fstab
	set dbell.ftp=service
	set dbell.ftp.server='ftp.dbellcloud.com'
	set dbell.ftp.port='21'
	set dbell.ftp.username='xxx@dbellcloud.com'
	set dbell.ftp.password='mypass'
	set dbell.ftp.enabled='1'
	set dbell.smtp=service
	set dbell.smtp.server='mail.dbell.ca'
	set dbell.smtp.port='465'
	set dbell.smtp.username='xxx@dbell.ca'
	set dbell.smtp.password='mypass'
	set dbell.smtp.subject='IPCam message'
	set dbell.smtp.owner='owner@my.device'
	set dbell.smtp.enabled='1'
	commit fstab

EOF


#echo "root:openipc" | chpasswd

echo "#" >/etc/opkg/distfeeds.conf

echo -e "#\n# Start checker\n#(while sleep 300; do if ! ping -q -c 6 8.8.8.8; then reboot; else echo 'Link to central node - OK' | logger; fi; done) &\n" >/etc/rc.local
echo -e "#\nexit 0\n" >>/etc/rc.local

exit 0
