#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='ZFT_Lab_flypeek'
	set system.@system[0].timezone='MSK-3'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	delete dhcp.lan.start
	delete dhcp.lan.limit
	delete dhcp.lan.leasetime
	set dhcp.lan.ignore='1'
	commit dhcp
	delete network.globals
	delete network.wan6
	commit network
	set wireless.radio0.channel='7'
	set wireless.radio0.disabled='0'
	set wireless.@wifi-iface[0].ssid='FreeTest'
	commit wireless
	set snmpd.default='snmpd'
	set snmpd.default.community='public'
	set snmpd.default.contact='Boss'
	set snmpd.default.location='World'
	set snmpd.default.interfaces='br-lan,3g-wan1'
	commit snmpd
	set mjpg-streamer.core.enabled='1'
	set mjpg-streamer.core.resolution='640x480'
	set mjpg-streamer.core.yuv='1'
	set mjpg-streamer.core.quality='80'
	set mjpg-streamer.core.fps='5'
	set mjpg-streamer.core.www='/www/webcam'
	set mjpg-streamer.core.port='8080'
	delete mjpg-streamer.core.username='openwrt'
	delete mjpg-streamer.core.password='openwrt'
	commit mjpg-streamer
EOF

exit 0
