#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set system.@system[0].hostname='White_telemetry'
	set system.@system[0].timezone='MSK-3'
	commit system
	delete dhcp.lan.dhcpv6
	delete dhcp.lan.ra
	commit dhcp
	delete network.globals
	delete network.wan6
	delete network.lan.ip6assign
	commit network
	set network.wan=interface
	set network.wan.type='bridge'
	set network.wan.proto='dhcp'
	commit network
	set network.wan2=interface
	set network.wan2.proto='3g'
	set network.wan2.device='/dev/ttyMODEM1'
	set network.wan2.service='umts'
	set network.wan2.apn='internet'
	set network.wan2.ipv6='0'
	set network.wan2.keepalive='3'
	set network.wan2.gpio='2'
	commit network
	set network.vtun0='interface'
	set network.vtun0.proto='vtun'
	set network.vtun0.server='vbox3.flymon.net'
	set network.vtun0.name='vbox4700'
	set network.vtun0.password='test2016'
	set network.vtun0.mode='tun'
	set network.vtun0.hub='172.19.24.1'
	set network.vtun0.ipaddr='172.19.24.100'
	commit network
	set wireless.radio0.channel='7'
	set wireless.radio0.disabled='0'
	set wireless.@wifi-iface[0].ssid='White_telemetry'
	commit wireless
EOF

echo -e "#\nexit 0\n" >/etc/rc.local

exit 0
