#!/bin/sh
#
# ZFT Lab. 2018 | http://zftlab.org/pages/2018010700.html
# Simple Plugin - Yandex


IPC=/mnt/mtd/ipcam.conf
TMP=/var/tmp


if [ -f ${IPC} ]; then
  while read settings
    do local ${settings}
  done < ${IPC}
  #
  export TZ=${time_zone}
  #
  # Enable Yandex.Disk
  if [ ${yandex_enable} = 1 ]; then
    if [ -f /bin/curl ]; then
      #
      if [ ${socks5_enable} = 1 ]; then
        curl_options="-s -k --socks5-hostname ${socks5_server}:${socks5_port} --proxy-user ${socks5_login}:${socks5_password}"
      else
        curl_options="-s -k"
      fi
      #
      FILE=$(date +%G%m%d'-'%H'-'%M'-'%S'.jpg')
      #FILE="$(date '+%G.%m.%d_%H:%M:%S')"
      PASSW=$(cat /mnt/mtd/Config/Account1 | jsonfilter -e '@.Users[@.Name="admin"].Password')
      curl -s -k --connect-timeout ${curl_timeout} --max-time ${curl_timeout} "http://127.0.0.1/webcapture.jpg?command=snap&channel=1&user=admin&password=${PASSW}" -o ${TMP}/snap.jpg >/dev/null 2>&1
      curl ${curl_options} --connect-timeout ${curl_timeout} --max-time ${curl_timeout} -X MKCOL -u "${yandex_login}:${yandex_password}" "https://webdav.yandex.ru/${yandex_folder}" >/dev/null 2>&1
      curl ${curl_options} --connect-timeout ${curl_timeout} --max-time ${curl_timeout} -X MKCOL -u "${yandex_login}:${yandex_password}" "https://webdav.yandex.ru/${yandex_folder}/${device_name}" >/dev/null 2>&1
      curl ${curl_options} --connect-timeout ${curl_timeout} --max-time ${curl_timeout} -u "${yandex_login}:${yandex_password}" -T "${TMP}/snap.jpg" "https://webdav.yandex.ru/${yandex_folder}/${device_name}/${FILE}" >/dev/null 2>&1
    fi
  fi
  #
fi

exit 0
