#!/bin/sh
#
# ZFT Lab. 2018 | http://zftlab.org/pages/2018010700.html
# Simple Plugin - WebDav


IPC=/mnt/mtd/ipcam.conf
TMP=/var/tmp


if [ -f ${IPC} ]; then
  while read settings
    do local ${settings}
  done < ${IPC}
  #
  export TZ=${time_zone}
  #
  # Enable WebDav
  if [ ${webdav_enable} = 1 ]; then
    if [ -f /bin/curl ]; then
      #
      if [ ${socks5_enable} = 1 ]; then
        curl_options="-s -k --socks5-hostname ${socks5_server}:${socks5_port} --proxy-user ${socks5_login}:${socks5_password}"
      else
        curl_options="-s -k"
      fi
      #
      STAMP="$(date '+%G.%m.%d_%H:%M:%S')"
      PASSW=$(cat /mnt/mtd/Config/Account1 | jsonfilter -e '@.Users[@.Name="admin"].Password')
      curl -s -k --connect-timeout ${curl_timeout} --max-time ${curl_timeout} "http://127.0.0.1/webcapture.jpg?command=snap&channel=1&user=admin&password=${PASSW}" -o ${TMP}/snap.jpg >/dev/null 2>&1
      curl ${curl_options} --connect-timeout ${curl_timeout} --max-time ${curl_timeout} -u "${webdav_login}:${webdav_password}" -T "${TMP}/snap.jpg" "http://${webdav_server}/~${webdav_login}/${device_tid}/$(date +%Y/%m/%d/%H.%M'.jpg')" >/dev/null 2>&1
    fi
  fi
  #
fi

exit 0
