#!/bin/sh

# register commit handler
[ -f /etc/config/ucitrack ] && \
[ "$(uci get ucitrack.@serialoverip[0] 2>/dev/null)" != "serialoverip" ] && \
uci batch <<-EOF >/dev/null 2>/dev/null
	add ucitrack serialoverip
	set ucitrack.@serialoverip[-1].init=serialoverip
	commit ucitrack
EOF

exit 0
