#!/bin/sh
#
# Reinitialization vtund
#
IFACE="wan2"

if [ "$INTERFACE" = "$IFACE" ]; then
  if [ "$ACTION" = "ifdown" ]; then
    (sleep 3; kill -s HUP `pidof vtund`) && echo "Reinitialization vtund..." | logger -t flyscript
  fi
  #
  if [ "$ACTION" = "ifup" ]; then
    (sleep 3; kill -s HUP `pidof vtund`) && echo "Reinitialization vtund..." | logger -t flyscript
  fi
fi

