#!/bin/sh /etc/rc.common
#
# Copyright (C) @FlyRouter

START=98

USE_PROCD=1
PROG=/usr/bin/load_hisilicon

start_service() {
  if [ $(uci_get "ipcam.video.disabled") = "0" ] ; then
    #
    #sensor=$(uci_get "ipcam.video.sensor")
    echo "Sensor: $(fw_printenv -n sensor)"
    #
    procd_open_instance
    procd_set_param command "$PROG" -i -sensor "$sensor"
    procd_close_instance
  else
    return 1
  fi
}
