#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=60

USE_PROCD=1
PROG=/usr/sbin/zabbix_agentd
CONFIG=/etc/zabbix_agentd.conf
PROG_NAME="Zabbix config agent"

start_service() {
	config_load zabbix_agentd
	allowroot=$(config_get zabbix_agentd AllowRoot)
	enable_remote_commands=$(config_get zabbix_agentd EnableRemoteCommands)
	hostname=$(config_get zabbix_agentd  Hostname)
	startagent=$(config_get zabbix_agentd StartAgents)
	server=$(config_get zabbix_agentd  Server)
	ACTserver=$(config_get zabbix_agentd  ActiveServer)
	include=$(config_get zabbix_agentd Include)  
	logfile=$(config_get zabbix_agentd LogFile)
	if [ $allowroot ]; then echo "AllowRoot=$allowroot" > $CONFIG; fi
	if [ $enable_remote_commands ]; then echo "EnableRemoteCommands=$enable_remote_commands" >> $CONFIG; fi
	if [ $hostname ]; then echo "Hostname=$hostname" >> $CONFIG; fi
	if [ $startagent ]; then echo "StartAgents=$startagent" >> $CONFIG; fi
	if [ $server ]; then echo "Server=$server" >> $CONFIG; fi
	if [ $ACTserver ]; then echo "ActiveServer=$ACTserver" >> $CONFIG; fi
	if [ $include ]; then echo "Include=$include" >> $CONFIG; fi
	if [ $logfile ]; then echo "LogFile=$logfile" >> $CONFIG; fi
	procd_open_instance
	procd_set_param command ${PROG} -c ${CONFIG} -f
	procd_set_param respawn
	procd_close_instance

	logger -s "$PROG_NAME started" \
               -t zabbix_agentd \
               -p daemon.info
}

service_triggers() {
	procd_add_reload_trigger zabbix_agentd
}

stop_service() {
	logger -s "$PROG_NAME stopping" \
		-t zabbix_agentd \
		-p daemon.info
}


reload_service() {
	logger -s "$PROG_NAME received reload trigger" \
		-t zabbix_agentd \
		-p daemon.info
	local control_file=/tmp/zabbix_agentd/applying_conf
        # avoid reloading while configuration is being applied
        # will wait for a maximum of 30 seconds
	for i in $(seq 1 30); do
		if [ -f $control_file ]; then
			sleep 1
		else
			break
		fi
	done
        # ensure control file is removed
	rm $control_file
        # reload
	start
}













