#!/bin/sh
#
# ZFT Lab. 2018 | http://zftlab.org/pages/2018010700.html
# Script for create web-x.cramfs.img


DATE=`date +%G%m%d`
HARD="IPC_HI3518E_50H10L_S39"
ARCH="web"
LOAD="0x00630000"
ENTR="0x00770000"


clear
rm -fv ${ARCH}-x.cramfs.img ${ARCH}-x.cramfs
#mkcramfs ./$ARCH ./${ARCH}-x.cramfs && \
mksquashfs ./${ARCH} ./${ARCH}-x.cramfs -noappend -no-progress -b 256k -comp xz && \
mkimage -A arm -O linux -T standalone -n linux -a "${LOAD}" -e "${ENTR}" -d ./${ARCH}-x.cramfs ./${ARCH}-x.cramfs.img && \
zip -D -X ${HARD}_${ARCH}_ZFTLAB-${DATE}.bin Install InstallDesc ${ARCH}-x.cramfs.img && \
mv ${HARD}_${ARCH}_ZFTLAB-${DATE}.bin ../ZFT_Lab/
echo ""
file web-x.cramfs web-x.cramfs.orig
echo ""
file web-x.cramfs.img*

