#!/bin/sh
#
# Serial converter CH-341
#
MPRODID="1a86/7523/254"
SYMLINK="ttyCOM"

if [ "${PRODUCT}" = "${MPRODID}" ]; then
  DEVICE=$(ls /sys/$DEVPATH/* | grep -e '^ttyUSB')
  NUMBER=$(echo ${DEVPATH} | tr '/:.' ' ' | awk '{print $7}')
  case "$ACTION" in
    add)
      if [ -z ${DEVICE} ]; then
        # logger -t flyscript "Warning, device name is empty..."
        exit 0
      else
        logger -t flyscript "Device name of serial converter - ${DEVICE}"
        ln -s /dev/$DEVICE /dev/${SYMLINK}${NUMBER} && logger -t flyscript "Symlink /dev/${SYMLINK}${NUMBER} created"
        (sleep 1; kill -s HUP `pidof ser2net`) && echo "Reinitialization ser2net..." | logger -t flyscript
      fi
      ;;
    remove)
      rm /dev/${SYMLINK}${NUMBER} && logger -t flyscript "Symlink /dev/${SYMLINK}${NUMBER} removed"
      ;;
    esac
fi

