#!/bin/sh
#
# Serial converter PL-2303
#
#MPRODID="67b/2303/400"
MPRODID="67b/2303/300"
SYMLINK="ttyCOM"

if [ "${PRODUCT}" = "${MPRODID}" ]; then
  DEVICE=$(ls /sys/$DEVPATH/* | grep -e '^ttyUSB')
  NUMBER=$(echo ${DEVPATH} | tr '/:.' ' ' | awk '{print $7}')
  case "$ACTION" in
    add)
      if [ -z ${DEVICE} ]; then
        #logger -t hotplug "Warning, device name is empty..."
        exit 0
      else
        logger -t hotplug "Device name of Serial Converter - ${DEVICE}"
        ln -s /dev/$DEVICE /dev/${SYMLINK}${NUMBER} && logger -t hotplug "Symlink /dev/${SYMLINK}${NUMBER} created"
      fi
      ;;
    remove)
      rm /dev/${SYMLINK}${NUMBER} && logger -t hotplug "Symlink /dev/${SYMLINK}${NUMBER} removed"
      ;;
    esac
fi

