#!/bin/sh
#
# HUAWEI E352
#
MODEM_PRODID="12d1/1506/102"
FIXED_DEVPATH="/devices/101c0000.ehci/usb1/1-1/1-1.2/1-1.2:1.0"
SYMLINK="ttyMODEM"


if [ "${PRODUCT}" = "${MODEM_PRODID}" ]; then
  if [ "${DEVPATH}" = "${FIXED_DEVPATH}" ]; then
    if [ "${ACTION}" = "add" ]; then
      DEVICE_NAME=$(ls /sys/$DEVPATH | grep -e '^ttyUSB')
      if [ -z ${DEVICE_NAME} ]; then
        logger -t flyscript "Warning DEVICE_NAME is empty"
        exit 0
      fi
      NUMBER=$(echo ${DEVPATH} | tr '/:.' ' ' | awk '{print $7}')
      logger -t flyscript "Device name of modem is $DEVICE_NAME"
      ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}${NUMBER}
      logger -t flyscript "Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK}${NUMBER} created"
    fi
  fi
fi


if [ "${PRODUCT}" = "${MODEM_PRODID}" ]; then
  if [ "${DEVPATH}" = "${FIXED_DEVPATH}" ]; then
    if [ "${ACTION}" = "remove" ]; then
      NUMBER=$(echo ${DEVPATH} | tr '/:.' ' ' | awk '{print $7}')
      rm -f /dev/${SYMLINK}${NUMBER}
      logger -t flyscript "Symlink /dev/${SYMLINK}${NUMBER} removed"
    fi
  fi
fi
