#!/bin/sh
#
# HUAWEI E171
#
MODEM_PRODID="12d1/1001/0"
#FIXED_DEVPATH="/devices/101c0000.ehci/usb1/1-1/1-1.6/1-1.6:1.0"
FIXED_DEVPATH="/devices/101c0000.ehci/usb1/1-1/1-1.2/1-1.2:1.0"
SYMLINK="ttyMODEMx"


if [ "${PRODUCT}" = "${MODEM_PRODID}" ]; then
  if [ "${DEVPATH}" = "${FIXED_DEVPATH}" ]; then
    if [ "${ACTION}" = "add" ]; then
      DEVICE_NAME=$(ls /sys/$DEVPATH | grep -e '^ttyUSB')
      if [ -z ${DEVICE_NAME} ]; then
        logger -t flyscript "Warning DEVICE_NAME is empty"
        exit 0
      fi
      logger -t flyscript "Device name of modem is $DEVICE_NAME"
      ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}
      logger -t flyscript "Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created"
    fi
  fi
fi


if [ "${PRODUCT}" = "${MODEM_PRODID}" ]; then
  if [ "${DEVPATH}" = "${FIXED_DEVPATH}" ]; then
    if [ "${ACTION}" = "remove" ]; then
      rm -f /dev/${SYMLINK}
      logger -t flyscript "Symlink /dev/${SYMLINK} removed"
    fi
  fi
fi
