#!/bin/sh
#
# GSM KyivStar UMW190 (secondary)
#
MODEM_PRODID="106c/3716/0"
SYMLINK="ttyUMW190"


if [ "${PRODUCT}" = "${MODEM_PRODID}" ];
  then if [ "${ACTION}" = "add" ];
    then
      DEVICE_NAME=$(ls /sys/$DEVPATH/* | grep -e '^ttyACM')
      if [ -z ${DEVICE_NAME} ];
        then
          # logger -t hotplug "Warning DEVICE_NAME is empty"
          exit 0
        exit
      fi
      logger -t hotplug "Device name of modem is $DEVICE_NAME"
      ln -s /dev/$DEVICE_NAME /dev/${SYMLINK}
      logger -t hotplug "Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created"
   fi
fi

if [ "${PRODUCT}" = "${MODEM_PRODID}" ];
  then if [ "${ACTION}" = "remove" ];
    then
      rm /dev/${SYMLINK}
      logger -t hotplug "Symlink /dev/${SYMLINK} removed"
  fi
fi
